### ISSUE TITLE
github integration (suspect commit, codeowner)

### ISSUE THREAD

**Issue by ndmanvar** [sentry-demos/sentry_react_native#45]
- [x] source code link
- [x] suspect commit
- [ ] codeowner

**Comment by krystofwoldrich** [comment]
Added source code link

[Example](https://testorg-az.sentry.io/issues/4438316682/events/76547b7b3c564b49937fc24111991ba9/)

<img width="300" alt="Screenshot 2023-09-05 at 12 45 14" src="https://github.com/sentry-demos/sentry_react_native/assets/31292499/6b5848e8-4877-4ab3-b6b7-77e042496c18">

**Comment by ndmanvar** [comment]
hmmm nice!
looks like suspect commit is not working though ): 
![image](https://github.com/sentry-demos/sentry_react_native/assets/314061/326ef68e-2e16-4fb6-87f5-87d91ff79577)

**Comment by krystofwoldrich** [comment]
[The suspect commits seem to be working too now.
](https://testorg-az.sentry.io/issues/4438316682/events/c34d4a0b2d614c2aa7c4464bc734eb12/)

It looks like there was some delay from me setting up the GitHub repo mapping to the project in Sentry and the suspect commit appearing in the issues.

<img width="1153" alt="Screenshot 2023-09-08 at 12 56 36" src="https://github.com/sentry-demos/sentry_react_native/assets/31292499/e082bd5b-0a01-4ccc-b876-1c6a6b77a21f">
